name: thermo-env
channels:
 - cantera
 - conda-forge
dependencies:
 - cantera
 - matplotlib
 - numpy
 - scipy
 - pint
 - coolprop
 - pandas
 - sympy
# dependencies for building book
 - pip:
    - jupyter-book
