name: rocket-env
channels:
 - cantera/label/dev
 - conda-forge
dependencies:
 - matplotlib
 - numpy
 - scipy
 - pint
 - pandas
 - cantera
 - fluids
# dependencies for building book
 - pip:
    - jupyter-book
